"""empty message

Revision ID: 2982b43d8fff
Revises: 6b3132df33e1
Create Date: 2021-03-15 14:32:13.640223

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import func


# revision identifiers, used by Alembic.
revision = '2982b43d8fff'
down_revision = '6b3132df33e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('multiple_choice_questions', sa.Column('updated_at', sa.DateTime(), server_default=func.now()))
    op.add_column('scale_questions', sa.Column('updated_at', sa.DateTime(), server_default=func.now()))
    op.add_column('screener_questions', sa.Column('updated_at', sa.DateTime(), server_default=func.now()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('screener_questions', 'updated_at')
    op.drop_column('scale_questions', 'updated_at')
    op.drop_column('multiple_choice_questions', 'updated_at')
    # ### end Alembic commands ###
