"""empty message

Revision ID: 2a340827192e
Revises: 
Create Date: 2021-01-02 19:19:56.674353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a340827192e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organisations', type_='foreignkey')
    op.drop_column('organisations', 'order_id')
    op.add_column('screener_questions', sa.Column('options', sa.String(length=64), nullable=True))
    op.add_column('screener_questions', sa.Column('required_answer', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_screener_questions_options'), 'screener_questions', ['options'], unique=False)
    op.create_index(op.f('ix_screener_questions_required_answer'), 'screener_questions', ['required_answer'], unique=False)
    op.drop_column('screener_questions', 'screener_answer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('screener_questions', sa.Column('screener_answer', sa.BOOLEAN(), nullable=True))
    op.drop_index(op.f('ix_screener_questions_required_answer'), table_name='screener_questions')
    op.drop_index(op.f('ix_screener_questions_options'), table_name='screener_questions')
    op.drop_column('screener_questions', 'required_answer')
    op.drop_column('screener_questions', 'options')
    op.add_column('organisations', sa.Column('order_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'organisations', 'order', ['order_id'], ['id'])
    # ### end Alembic commands ###
