"""empty message

Revision ID: 5551fa0c79c4
Revises: 
Create Date: 2021-03-10 15:38:24.475922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5551fa0c79c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blog_news_letters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('blog_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('editableHTML',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('editor_name', sa.String(length=100), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('editor_name')
    )
    op.create_table('hometext',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstext', sa.String(length=80), nullable=False),
    sa.Column('secondtext', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logo_image', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('long_description', sa.Text(), nullable=False),
    sa.Column('demo_url', sa.String(length=256), nullable=False),
    sa.Column('code_path', sa.String(length=256), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('support_price', sa.Float(), nullable=False),
    sa.Column('image_filename', sa.String(length=256), nullable=False),
    sa.Column('tags', sa.Text(), nullable=False),
    sa.Column('release_date', sa.DateTime(), nullable=False),
    sa.Column('last_update_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('index', sa.String(length=64), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    op.create_table('seo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meta_tag', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('content', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('value', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('slide_show_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('image_filename', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stripe_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('payment_intent', sa.String(length=180), nullable=True),
    sa.Column('customer_email', sa.String(length=64), nullable=True),
    sa.Column('customer', sa.String(length=64), nullable=True),
    sa.Column('customer_details', sa.String(length=64), nullable=True),
    sa.Column('client_reference_id', sa.String(length=64), nullable=True),
    sa.Column('payment_method', sa.String(length=10), nullable=True),
    sa.Column('payment_status', sa.String(length=10), nullable=True),
    sa.Column('amount_total', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=90), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stripe_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_intent', sa.String(length=180), nullable=True),
    sa.Column('outcome', sa.String(length=64), nullable=True),
    sa.Column('customer', sa.String(length=64), nullable=True),
    sa.Column('payment_method', sa.String(length=10), nullable=True),
    sa.Column('payment_method_details', sa.String(length=10), nullable=True),
    sa.Column('billing_details', sa.String(length=10), nullable=True),
    sa.Column('disputed', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('application_fee_amount', sa.Integer(), nullable=True),
    sa.Column('receipt_url', sa.String(length=64), nullable=True),
    sa.Column('type', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('technologies_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('technologies_text',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstext', sa.String(length=80), nullable=False),
    sa.Column('secondtext', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tracking_script',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('script', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('module_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_filename', sa.String(length=256), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('is_respondent', sa.Boolean(), nullable=True),
    sa.Column('is_organisation', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_first_name'), 'users', ['first_name'], unique=False)
    op.create_index(op.f('ix_users_last_name'), 'users', ['last_name'], unique=False)
    op.create_table('blog_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organisations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('org_name', sa.String(length=255), nullable=True),
    sa.Column('org_city', sa.String(length=255), nullable=True),
    sa.Column('org_state', sa.String(length=255), nullable=True),
    sa.Column('org_country', sa.String(length=255), nullable=True),
    sa.Column('org_website', sa.String(length=255), nullable=True),
    sa.Column('org_industry', sa.String(length=255), nullable=True),
    sa.Column('mobile_phone', sa.BigInteger(), nullable=True),
    sa.Column('org_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organisations_mobile_phone'), 'organisations', ['mobile_phone'], unique=True)
    op.create_table('blog_post_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['blog_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['blog_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blog_post_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('lft', sa.Integer(), nullable=False),
    sa.Column('rgt', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('tree_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['blog_post_comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['blog_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('blog_post_comments_level_idx', 'blog_post_comments', ['level'], unique=False)
    op.create_index('blog_post_comments_lft_idx', 'blog_post_comments', ['lft'], unique=False)
    op.create_index('blog_post_comments_rgt_idx', 'blog_post_comments', ['rgt'], unique=False)
    op.create_table('blog_post_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['blog_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['blog_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('org_staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('invited_by', sa.Integer(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('order_quantity', sa.Integer(), nullable=True),
    sa.Column('service_type', sa.String(length=150), nullable=True),
    sa.Column('currency', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_name'), 'project', ['name'], unique=False)
    op.create_table('line_items',
    sa.Column('line_item_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('service_type', sa.String(length=10), nullable=True),
    sa.Column('unit_amount', sa.Integer(), nullable=True),
    sa.Column('tax_amount', sa.Integer(), nullable=True),
    sa.Column('tax_percentage', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('line_item_id')
    )
    op.create_index(op.f('ix_line_items_name'), 'line_items', ['name'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('question_type', sa.String(length=64), nullable=True),
    sa.Column('multiple_choice_option_one', sa.String(length=64), nullable=True),
    sa.Column('multiple_choice_option_two', sa.String(length=64), nullable=True),
    sa.Column('multiple_choice_option_three', sa.String(length=64), nullable=True),
    sa.Column('multiple_choice_option_four', sa.String(length=64), nullable=True),
    sa.Column('multiple_choice_option_five', sa.String(length=64), nullable=True),
    sa.Column('option_one', sa.String(length=64), nullable=True),
    sa.Column('option_two', sa.String(length=64), nullable=True),
    sa.Column('option_three', sa.String(length=64), nullable=True),
    sa.Column('option_four', sa.String(length=64), nullable=True),
    sa.Column('option_five', sa.String(length=64), nullable=True),
    sa.Column('option_one_scale', sa.Integer(), nullable=True),
    sa.Column('option_two_scale', sa.Integer(), nullable=True),
    sa.Column('option_three_scale', sa.Integer(), nullable=True),
    sa.Column('option_four_scale', sa.Integer(), nullable=True),
    sa.Column('option_five_scale', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_question_type'), 'questions', ['question_type'], unique=False)
    op.create_index(op.f('ix_questions_timestamp'), 'questions', ['timestamp'], unique=False)
    op.create_table('multiple_choice_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=90), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('multiple_choice_option_one', sa.String(length=64), nullable=True),
    sa.Column('multiple_choice_option_two', sa.String(length=64), nullable=True),
    sa.Column('multiple_choice_option_three', sa.String(length=64), nullable=True),
    sa.Column('multiple_choice_option_four', sa.String(length=64), nullable=True),
    sa.Column('multiple_choice_option_five', sa.String(length=64), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_multiple_choice_questions_multiple_choice_option_five'), 'multiple_choice_questions', ['multiple_choice_option_five'], unique=False)
    op.create_index(op.f('ix_multiple_choice_questions_multiple_choice_option_four'), 'multiple_choice_questions', ['multiple_choice_option_four'], unique=False)
    op.create_index(op.f('ix_multiple_choice_questions_multiple_choice_option_one'), 'multiple_choice_questions', ['multiple_choice_option_one'], unique=False)
    op.create_index(op.f('ix_multiple_choice_questions_multiple_choice_option_three'), 'multiple_choice_questions', ['multiple_choice_option_three'], unique=False)
    op.create_index(op.f('ix_multiple_choice_questions_multiple_choice_option_two'), 'multiple_choice_questions', ['multiple_choice_option_two'], unique=False)
    op.create_index(op.f('ix_multiple_choice_questions_title'), 'multiple_choice_questions', ['title'], unique=False)
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('line_item_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('payment_intent', sa.String(length=180), nullable=True),
    sa.Column('customer_email', sa.String(length=64), nullable=True),
    sa.Column('payment_method', sa.String(length=10), nullable=True),
    sa.Column('payment_status', sa.String(length=10), nullable=True),
    sa.Column('total_amount', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=90), nullable=True),
    sa.Column('delivered', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['line_item_id'], ['line_items.line_item_id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scale_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=90), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('options', sa.String(length=64), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scale_questions_options'), 'scale_questions', ['options'], unique=False)
    op.create_index(op.f('ix_scale_questions_title'), 'scale_questions', ['title'], unique=False)
    op.create_table('screener_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=90), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('required_answer', sa.String(length=64), nullable=True),
    sa.Column('answer_option_one', sa.String(length=64), nullable=True),
    sa.Column('answer_option_two', sa.String(length=64), nullable=True),
    sa.Column('answer_option_three', sa.String(length=64), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screener_questions_answer_option_one'), 'screener_questions', ['answer_option_one'], unique=False)
    op.create_index(op.f('ix_screener_questions_answer_option_three'), 'screener_questions', ['answer_option_three'], unique=False)
    op.create_index(op.f('ix_screener_questions_answer_option_two'), 'screener_questions', ['answer_option_two'], unique=False)
    op.create_index(op.f('ix_screener_questions_question'), 'screener_questions', ['question'], unique=False)
    op.create_index(op.f('ix_screener_questions_required_answer'), 'screener_questions', ['required_answer'], unique=False)
    op.create_table('answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_city', sa.String(), nullable=True),
    sa.Column('location_state', sa.String(), nullable=True),
    sa.Column('location_ip_address', sa.String(), nullable=True),
    sa.Column('multiple_choice_answer_one', sa.String(length=64), nullable=True),
    sa.Column('multiple_choice_answer_two', sa.String(length=64), nullable=True),
    sa.Column('multiple_choice_answer_three', sa.String(length=64), nullable=True),
    sa.Column('multiple_choice_answer_four', sa.String(length=64), nullable=True),
    sa.Column('multiple_choice_answer_five', sa.String(length=64), nullable=True),
    sa.Column('option_one_answer', sa.String(length=64), nullable=True),
    sa.Column('option_two_answer', sa.String(length=64), nullable=True),
    sa.Column('option_three_answer', sa.String(length=64), nullable=True),
    sa.Column('option_four_answer', sa.String(length=64), nullable=True),
    sa.Column('option_five_answer', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('scale_questions_id', sa.Integer(), nullable=True),
    sa.Column('multiple_choice_questions_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['multiple_choice_questions_id'], ['multiple_choice_questions.id'], ),
    sa.ForeignKeyConstraint(['scale_questions_id'], ['scale_questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answers_location_city'), 'answers', ['location_city'], unique=False)
    op.create_index(op.f('ix_answers_location_ip_address'), 'answers', ['location_ip_address'], unique=False)
    op.create_index(op.f('ix_answers_location_state'), 'answers', ['location_state'], unique=False)
    op.create_index(op.f('ix_answers_multiple_choice_answer_five'), 'answers', ['multiple_choice_answer_five'], unique=False)
    op.create_index(op.f('ix_answers_multiple_choice_answer_four'), 'answers', ['multiple_choice_answer_four'], unique=False)
    op.create_index(op.f('ix_answers_multiple_choice_answer_one'), 'answers', ['multiple_choice_answer_one'], unique=False)
    op.create_index(op.f('ix_answers_multiple_choice_answer_three'), 'answers', ['multiple_choice_answer_three'], unique=False)
    op.create_index(op.f('ix_answers_multiple_choice_answer_two'), 'answers', ['multiple_choice_answer_two'], unique=False)
    op.create_index(op.f('ix_answers_option_five_answer'), 'answers', ['option_five_answer'], unique=False)
    op.create_index(op.f('ix_answers_option_four_answer'), 'answers', ['option_four_answer'], unique=False)
    op.create_index(op.f('ix_answers_option_one_answer'), 'answers', ['option_one_answer'], unique=False)
    op.create_index(op.f('ix_answers_option_three_answer'), 'answers', ['option_three_answer'], unique=False)
    op.create_index(op.f('ix_answers_option_two_answer'), 'answers', ['option_two_answer'], unique=False)
    op.create_table('multiple_choice_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('multiple_choice_answer_one', sa.String(length=64), nullable=True),
    sa.Column('multiple_choice_answer_two', sa.String(length=64), nullable=True),
    sa.Column('multiple_choice_answer_three', sa.String(length=64), nullable=True),
    sa.Column('multiple_choice_answer_four', sa.String(length=64), nullable=True),
    sa.Column('multiple_choice_answer_five', sa.String(length=64), nullable=True),
    sa.Column('multiple_choice_question_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['multiple_choice_question_id'], ['multiple_choice_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_multiple_choice_answers_multiple_choice_answer_five'), 'multiple_choice_answers', ['multiple_choice_answer_five'], unique=False)
    op.create_index(op.f('ix_multiple_choice_answers_multiple_choice_answer_four'), 'multiple_choice_answers', ['multiple_choice_answer_four'], unique=False)
    op.create_index(op.f('ix_multiple_choice_answers_multiple_choice_answer_one'), 'multiple_choice_answers', ['multiple_choice_answer_one'], unique=False)
    op.create_index(op.f('ix_multiple_choice_answers_multiple_choice_answer_three'), 'multiple_choice_answers', ['multiple_choice_answer_three'], unique=False)
    op.create_index(op.f('ix_multiple_choice_answers_multiple_choice_answer_two'), 'multiple_choice_answers', ['multiple_choice_answer_two'], unique=False)
    op.create_table('paid_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('respondent_id', sa.Integer(), nullable=True),
    sa.Column('question', sa.String(), nullable=True),
    sa.Column('question_type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('answer', sa.String(), nullable=True),
    sa.Column('answer_option_one', sa.String(), nullable=True),
    sa.Column('answer_option_two', sa.String(), nullable=True),
    sa.Column('answer_option_three', sa.String(), nullable=True),
    sa.Column('answer_option_four', sa.String(), nullable=True),
    sa.Column('answer_option_five', sa.String(), nullable=True),
    sa.Column('respondent_location', sa.String(), nullable=True),
    sa.Column('project_name', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paid_projects_project_name'), 'paid_projects', ['project_name'], unique=False)
    op.create_table('scale_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scale_question_id', sa.Integer(), nullable=True),
    sa.Column('option', sa.String(length=64), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['scale_question_id'], ['scale_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scale_answers_option'), 'scale_answers', ['option'], unique=False)
    op.create_table('screener_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer_option_one', sa.String(length=64), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('screener_questions_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['screener_questions_id'], ['screener_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screener_answers_answer_option_one'), 'screener_answers', ['answer_option_one'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_screener_answers_answer_option_one'), table_name='screener_answers')
    op.drop_table('screener_answers')
    op.drop_index(op.f('ix_scale_answers_option'), table_name='scale_answers')
    op.drop_table('scale_answers')
    op.drop_index(op.f('ix_paid_projects_project_name'), table_name='paid_projects')
    op.drop_table('paid_projects')
    op.drop_index(op.f('ix_multiple_choice_answers_multiple_choice_answer_two'), table_name='multiple_choice_answers')
    op.drop_index(op.f('ix_multiple_choice_answers_multiple_choice_answer_three'), table_name='multiple_choice_answers')
    op.drop_index(op.f('ix_multiple_choice_answers_multiple_choice_answer_one'), table_name='multiple_choice_answers')
    op.drop_index(op.f('ix_multiple_choice_answers_multiple_choice_answer_four'), table_name='multiple_choice_answers')
    op.drop_index(op.f('ix_multiple_choice_answers_multiple_choice_answer_five'), table_name='multiple_choice_answers')
    op.drop_table('multiple_choice_answers')
    op.drop_index(op.f('ix_answers_option_two_answer'), table_name='answers')
    op.drop_index(op.f('ix_answers_option_three_answer'), table_name='answers')
    op.drop_index(op.f('ix_answers_option_one_answer'), table_name='answers')
    op.drop_index(op.f('ix_answers_option_four_answer'), table_name='answers')
    op.drop_index(op.f('ix_answers_option_five_answer'), table_name='answers')
    op.drop_index(op.f('ix_answers_multiple_choice_answer_two'), table_name='answers')
    op.drop_index(op.f('ix_answers_multiple_choice_answer_three'), table_name='answers')
    op.drop_index(op.f('ix_answers_multiple_choice_answer_one'), table_name='answers')
    op.drop_index(op.f('ix_answers_multiple_choice_answer_four'), table_name='answers')
    op.drop_index(op.f('ix_answers_multiple_choice_answer_five'), table_name='answers')
    op.drop_index(op.f('ix_answers_location_state'), table_name='answers')
    op.drop_index(op.f('ix_answers_location_ip_address'), table_name='answers')
    op.drop_index(op.f('ix_answers_location_city'), table_name='answers')
    op.drop_table('answers')
    op.drop_index(op.f('ix_screener_questions_required_answer'), table_name='screener_questions')
    op.drop_index(op.f('ix_screener_questions_question'), table_name='screener_questions')
    op.drop_index(op.f('ix_screener_questions_answer_option_two'), table_name='screener_questions')
    op.drop_index(op.f('ix_screener_questions_answer_option_three'), table_name='screener_questions')
    op.drop_index(op.f('ix_screener_questions_answer_option_one'), table_name='screener_questions')
    op.drop_table('screener_questions')
    op.drop_index(op.f('ix_scale_questions_title'), table_name='scale_questions')
    op.drop_index(op.f('ix_scale_questions_options'), table_name='scale_questions')
    op.drop_table('scale_questions')
    op.drop_table('order')
    op.drop_index(op.f('ix_multiple_choice_questions_title'), table_name='multiple_choice_questions')
    op.drop_index(op.f('ix_multiple_choice_questions_multiple_choice_option_two'), table_name='multiple_choice_questions')
    op.drop_index(op.f('ix_multiple_choice_questions_multiple_choice_option_three'), table_name='multiple_choice_questions')
    op.drop_index(op.f('ix_multiple_choice_questions_multiple_choice_option_one'), table_name='multiple_choice_questions')
    op.drop_index(op.f('ix_multiple_choice_questions_multiple_choice_option_four'), table_name='multiple_choice_questions')
    op.drop_index(op.f('ix_multiple_choice_questions_multiple_choice_option_five'), table_name='multiple_choice_questions')
    op.drop_table('multiple_choice_questions')
    op.drop_index(op.f('ix_questions_timestamp'), table_name='questions')
    op.drop_index(op.f('ix_questions_question_type'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_line_items_name'), table_name='line_items')
    op.drop_table('line_items')
    op.drop_index(op.f('ix_project_name'), table_name='project')
    op.drop_table('project')
    op.drop_table('org_staff')
    op.drop_table('blog_post_tags')
    op.drop_index('blog_post_comments_rgt_idx', table_name='blog_post_comments')
    op.drop_index('blog_post_comments_lft_idx', table_name='blog_post_comments')
    op.drop_index('blog_post_comments_level_idx', table_name='blog_post_comments')
    op.drop_table('blog_post_comments')
    op.drop_table('blog_post_categories')
    op.drop_index(op.f('ix_organisations_mobile_phone'), table_name='organisations')
    op.drop_table('organisations')
    op.drop_table('blog_posts')
    op.drop_index(op.f('ix_users_last_name'), table_name='users')
    op.drop_index(op.f('ix_users_first_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('module_images')
    op.drop_table('tracking_script')
    op.drop_table('technologies_text')
    op.drop_table('technologies_images')
    op.drop_table('stripe_events')
    op.drop_table('stripe_data')
    op.drop_table('slide_show_images')
    op.drop_table('settings')
    op.drop_table('seo')
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_table('roles')
    op.drop_table('modules')
    op.drop_table('logo')
    op.drop_table('hometext')
    op.drop_table('editableHTML')
    op.drop_table('blog_tags')
    op.drop_table('blog_news_letters')
    op.drop_table('blog_categories')
    # ### end Alembic commands ###
