"""empty message

Revision ID: 653ae6419ccc
Revises: 0f3678996d01
Create Date: 2021-03-15 15:03:15.002677

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import func


# revision identifiers, used by Alembic.
revision = '653ae6419ccc'
down_revision = '0f3678996d01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scale_questions', sa.Column('created_at', sa.DateTime(), server_default=func.now()))
    op.create_index(op.f('ix_scale_questions_created_at'), 'scale_questions', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scale_questions_created_at'), table_name='scale_questions')
    op.drop_column('scale_questions', 'created_at')
    # ### end Alembic commands ###
