"""empty message

Revision ID: 6b3132df33e1
Revises: 7816d67fd16f
Create Date: 2021-03-15 14:31:24.536868

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6b3132df33e1'
down_revision = '7816d67fd16f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('multiple_choice_questions', 'updated_at')
    op.drop_column('scale_questions', 'updated_at')
    op.drop_column('screener_questions', 'updated_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('screener_questions', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('scale_questions', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('multiple_choice_questions', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
