"""empty message

Revision ID: 7816d67fd16f
Revises: abd8b613aede
Create Date: 2021-03-15 14:30:13.075515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7816d67fd16f'
down_revision = 'abd8b613aede'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('multiple_choice_questions', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('multiple_choice_questions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_multiple_choice_questions_created_at'), 'multiple_choice_questions', ['created_at'], unique=False)
    op.add_column('scale_questions', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('scale_questions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_scale_questions_created_at'), 'scale_questions', ['created_at'], unique=False)
    op.add_column('screener_questions', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('screener_questions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_screener_questions_created_at'), 'screener_questions', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_screener_questions_created_at'), table_name='screener_questions')
    op.drop_column('screener_questions', 'updated_at')
    op.drop_column('screener_questions', 'created_at')
    op.drop_index(op.f('ix_scale_questions_created_at'), table_name='scale_questions')
    op.drop_column('scale_questions', 'updated_at')
    op.drop_column('scale_questions', 'created_at')
    op.drop_index(op.f('ix_multiple_choice_questions_created_at'), table_name='multiple_choice_questions')
    op.drop_column('multiple_choice_questions', 'updated_at')
    op.drop_column('multiple_choice_questions', 'created_at')
    # ### end Alembic commands ###
