"""empty message

Revision ID: 88ebd18ef240
Revises: 51f8f2ef9d06
Create Date: 2021-03-11 11:20:35.999599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88ebd18ef240'
down_revision = '51f8f2ef9d06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('screener_questions', sa.Column('question_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'screener_questions', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'screener_questions', type_='foreignkey')
    op.drop_column('screener_questions', 'question_id')
    # ### end Alembic commands ###
