"""empty message

Revision ID: 96e35d722836
Revises: 7a64823eceb1
Create Date: 2021-03-15 11:09:33.921903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96e35d722836'
down_revision = '7a64823eceb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('multiple_choice_questions', sa.Column('organisation_id', sa.Integer(), nullable=True))
    op.add_column('multiple_choice_questions', sa.Column('project_id', sa.Integer(), nullable=True))
    op.add_column('multiple_choice_questions', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'multiple_choice_questions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'multiple_choice_questions', 'organisations', ['organisation_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'multiple_choice_questions', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('questions_organisation_id_fkey', 'questions', type_='foreignkey')
    op.drop_constraint('questions_project_id_fkey', 'questions', type_='foreignkey')
    op.drop_constraint('questions_user_id_fkey', 'questions', type_='foreignkey')
    op.drop_column('questions', 'organisation_id')
    op.drop_column('questions', 'project_id')
    op.drop_column('questions', 'user_id')
    op.add_column('scale_questions', sa.Column('organisation_id', sa.Integer(), nullable=True))
    op.add_column('scale_questions', sa.Column('project_id', sa.Integer(), nullable=True))
    op.add_column('scale_questions', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'scale_questions', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'scale_questions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'scale_questions', 'organisations', ['organisation_id'], ['id'], ondelete='CASCADE')
    op.add_column('screener_questions', sa.Column('organisation_id', sa.Integer(), nullable=True))
    op.add_column('screener_questions', sa.Column('project_id', sa.Integer(), nullable=True))
    op.add_column('screener_questions', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'screener_questions', 'organisations', ['organisation_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'screener_questions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'screener_questions', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'screener_questions', type_='foreignkey')
    op.drop_constraint(None, 'screener_questions', type_='foreignkey')
    op.drop_constraint(None, 'screener_questions', type_='foreignkey')
    op.drop_column('screener_questions', 'user_id')
    op.drop_column('screener_questions', 'project_id')
    op.drop_column('screener_questions', 'organisation_id')
    op.drop_constraint(None, 'scale_questions', type_='foreignkey')
    op.drop_constraint(None, 'scale_questions', type_='foreignkey')
    op.drop_constraint(None, 'scale_questions', type_='foreignkey')
    op.drop_column('scale_questions', 'user_id')
    op.drop_column('scale_questions', 'project_id')
    op.drop_column('scale_questions', 'organisation_id')
    op.add_column('questions', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('questions', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('questions', sa.Column('organisation_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('questions_user_id_fkey', 'questions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('questions_project_id_fkey', 'questions', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('questions_organisation_id_fkey', 'questions', 'organisations', ['organisation_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'multiple_choice_questions', type_='foreignkey')
    op.drop_constraint(None, 'multiple_choice_questions', type_='foreignkey')
    op.drop_constraint(None, 'multiple_choice_questions', type_='foreignkey')
    op.drop_column('multiple_choice_questions', 'user_id')
    op.drop_column('multiple_choice_questions', 'project_id')
    op.drop_column('multiple_choice_questions', 'organisation_id')
    # ### end Alembic commands ###
