"""empty message

Revision ID: a764405165f3
Revises: 
Create Date: 2021-01-02 23:53:04.769548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a764405165f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organisations', type_='foreignkey')
    op.drop_column('organisations', 'order_id')
    op.add_column('question', sa.Column('organisation_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'question', 'organisations', ['organisation_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_scale_questions_answer_options', table_name='scale_questions')
    op.drop_column('scale_questions', 'answer_options')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scale_questions', sa.Column('answer_options', sa.VARCHAR(length=64), nullable=True))
    op.create_index('ix_scale_questions_answer_options', 'scale_questions', ['answer_options'], unique=False)
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.drop_column('question', 'organisation_id')
    op.add_column('organisations', sa.Column('order_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'organisations', 'order', ['order_id'], ['id'])
    # ### end Alembic commands ###
