"""empty message

Revision ID: abd8b613aede
Revises: cf4d4d621167
Create Date: 2021-03-15 12:10:38.910786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abd8b613aede'
down_revision = 'cf4d4d621167'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('multiple_choice_questions_organisation_id_fkey', 'multiple_choice_questions', type_='foreignkey')
    op.drop_constraint('multiple_choice_questions_project_id_fkey', 'multiple_choice_questions', type_='foreignkey')
    op.drop_constraint('multiple_choice_questions_user_id_fkey', 'multiple_choice_questions', type_='foreignkey')
    op.drop_column('multiple_choice_questions', 'user_id')
    op.drop_column('multiple_choice_questions', 'project_id')
    op.drop_column('multiple_choice_questions', 'organisation_id')
    op.add_column('questions', sa.Column('organisation_id', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('project_id', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'questions', 'organisations', ['organisation_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'questions', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'questions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('scale_questions_user_id_fkey', 'scale_questions', type_='foreignkey')
    op.drop_constraint('scale_questions_organisation_id_fkey', 'scale_questions', type_='foreignkey')
    op.drop_constraint('scale_questions_project_id_fkey', 'scale_questions', type_='foreignkey')
    op.drop_column('scale_questions', 'project_id')
    op.drop_column('scale_questions', 'organisation_id')
    op.drop_column('scale_questions', 'user_id')
    op.drop_constraint('screener_questions_organisation_id_fkey', 'screener_questions', type_='foreignkey')
    op.drop_constraint('screener_questions_user_id_fkey', 'screener_questions', type_='foreignkey')
    op.drop_constraint('screener_questions_project_id_fkey', 'screener_questions', type_='foreignkey')
    op.drop_column('screener_questions', 'user_id')
    op.drop_column('screener_questions', 'project_id')
    op.drop_column('screener_questions', 'organisation_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('screener_questions', sa.Column('organisation_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('screener_questions', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('screener_questions', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('screener_questions_project_id_fkey', 'screener_questions', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('screener_questions_user_id_fkey', 'screener_questions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('screener_questions_organisation_id_fkey', 'screener_questions', 'organisations', ['organisation_id'], ['id'], ondelete='CASCADE')
    op.add_column('scale_questions', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('scale_questions', sa.Column('organisation_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('scale_questions', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('scale_questions_project_id_fkey', 'scale_questions', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('scale_questions_organisation_id_fkey', 'scale_questions', 'organisations', ['organisation_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('scale_questions_user_id_fkey', 'scale_questions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_column('questions', 'user_id')
    op.drop_column('questions', 'project_id')
    op.drop_column('questions', 'organisation_id')
    op.add_column('multiple_choice_questions', sa.Column('organisation_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('multiple_choice_questions', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('multiple_choice_questions', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('multiple_choice_questions_user_id_fkey', 'multiple_choice_questions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('multiple_choice_questions_project_id_fkey', 'multiple_choice_questions', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('multiple_choice_questions_organisation_id_fkey', 'multiple_choice_questions', 'organisations', ['organisation_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
