"""empty message

Revision ID: bba9b254ef3f
Revises: 2982b43d8fff
Create Date: 2021-03-15 14:58:43.730150

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bba9b254ef3f'
down_revision = '2982b43d8fff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_multiple_choice_questions_created_at', table_name='multiple_choice_questions')
    op.drop_column('multiple_choice_questions', 'created_at')
    op.drop_index('ix_scale_questions_created_at', table_name='scale_questions')
    op.drop_column('scale_questions', 'created_at')
    op.drop_index('ix_screener_questions_created_at', table_name='screener_questions')
    op.drop_column('screener_questions', 'created_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('screener_questions', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index('ix_screener_questions_created_at', 'screener_questions', ['created_at'], unique=False)
    op.add_column('scale_questions', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index('ix_scale_questions_created_at', 'scale_questions', ['created_at'], unique=False)
    op.add_column('multiple_choice_questions', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index('ix_multiple_choice_questions_created_at', 'multiple_choice_questions', ['created_at'], unique=False)
    # ### end Alembic commands ###
