"""empty message

Revision ID: cf4d4d621167
Revises: ff951652e333
Create Date: 2021-03-15 11:23:22.889100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf4d4d621167'
down_revision = 'ff951652e333'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('questions_user_id_fkey', 'questions', type_='foreignkey')
    op.drop_constraint('questions_project_id_fkey', 'questions', type_='foreignkey')
    op.drop_constraint('questions_organisation_id_fkey', 'questions', type_='foreignkey')
    op.drop_column('questions', 'project_id')
    op.drop_column('questions', 'organisation_id')
    op.drop_column('questions', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('questions', sa.Column('organisation_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('questions', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('questions_organisation_id_fkey', 'questions', 'organisations', ['organisation_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('questions_project_id_fkey', 'questions', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('questions_user_id_fkey', 'questions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
