"""empty message

Revision ID: f882b1a4f625
Revises: 
Create Date: 2021-01-03 21:00:40.833617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f882b1a4f625'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('multiple_choice_questions', sa.Column('option_five', sa.String(length=64), nullable=True))
    op.add_column('multiple_choice_questions', sa.Column('option_four', sa.String(length=64), nullable=True))
    op.add_column('multiple_choice_questions', sa.Column('option_one', sa.String(length=64), nullable=True))
    op.add_column('multiple_choice_questions', sa.Column('option_three', sa.String(length=64), nullable=True))
    op.add_column('multiple_choice_questions', sa.Column('option_two', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_multiple_choice_questions_option_five'), 'multiple_choice_questions', ['option_five'], unique=False)
    op.create_index(op.f('ix_multiple_choice_questions_option_four'), 'multiple_choice_questions', ['option_four'], unique=False)
    op.create_index(op.f('ix_multiple_choice_questions_option_one'), 'multiple_choice_questions', ['option_one'], unique=False)
    op.create_index(op.f('ix_multiple_choice_questions_option_three'), 'multiple_choice_questions', ['option_three'], unique=False)
    op.create_index(op.f('ix_multiple_choice_questions_option_two'), 'multiple_choice_questions', ['option_two'], unique=False)
    op.add_column('options', sa.Column('option_five', sa.String(length=64), nullable=True))
    op.add_column('options', sa.Column('option_four', sa.String(length=64), nullable=True))
    op.add_column('options', sa.Column('option_one', sa.String(length=64), nullable=True))
    op.add_column('options', sa.Column('option_three', sa.String(length=64), nullable=True))
    op.add_column('options', sa.Column('option_two', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_options_option_five'), 'options', ['option_five'], unique=False)
    op.create_index(op.f('ix_options_option_four'), 'options', ['option_four'], unique=False)
    op.create_index(op.f('ix_options_option_one'), 'options', ['option_one'], unique=False)
    op.create_index(op.f('ix_options_option_three'), 'options', ['option_three'], unique=False)
    op.create_index(op.f('ix_options_option_two'), 'options', ['option_two'], unique=False)
    op.drop_index('ix_options_text', table_name='options')
    op.drop_column('options', 'text')
    op.drop_constraint(None, 'organisations', type_='foreignkey')
    op.drop_column('organisations', 'order_id')
    op.create_foreign_key(None, 'question', 'organisations', ['organisation_id'], ['id'], ondelete='CASCADE')
    op.add_column('scale_questions', sa.Column('option_five', sa.String(length=64), nullable=True))
    op.add_column('scale_questions', sa.Column('option_five_scale', sa.String(length=64), nullable=True))
    op.add_column('scale_questions', sa.Column('option_four', sa.String(length=64), nullable=True))
    op.add_column('scale_questions', sa.Column('option_four_scale', sa.String(length=64), nullable=True))
    op.add_column('scale_questions', sa.Column('option_one', sa.String(length=64), nullable=True))
    op.add_column('scale_questions', sa.Column('option_one_scale', sa.String(length=64), nullable=True))
    op.add_column('scale_questions', sa.Column('option_three', sa.String(length=64), nullable=True))
    op.add_column('scale_questions', sa.Column('option_three_scale', sa.String(length=64), nullable=True))
    op.add_column('scale_questions', sa.Column('option_two', sa.String(length=64), nullable=True))
    op.add_column('scale_questions', sa.Column('option_two_scale', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_scale_questions_option_five'), 'scale_questions', ['option_five'], unique=False)
    op.create_index(op.f('ix_scale_questions_option_five_scale'), 'scale_questions', ['option_five_scale'], unique=False)
    op.create_index(op.f('ix_scale_questions_option_four'), 'scale_questions', ['option_four'], unique=False)
    op.create_index(op.f('ix_scale_questions_option_four_scale'), 'scale_questions', ['option_four_scale'], unique=False)
    op.create_index(op.f('ix_scale_questions_option_one'), 'scale_questions', ['option_one'], unique=False)
    op.create_index(op.f('ix_scale_questions_option_one_scale'), 'scale_questions', ['option_one_scale'], unique=False)
    op.create_index(op.f('ix_scale_questions_option_three'), 'scale_questions', ['option_three'], unique=False)
    op.create_index(op.f('ix_scale_questions_option_three_scale'), 'scale_questions', ['option_three_scale'], unique=False)
    op.create_index(op.f('ix_scale_questions_option_two'), 'scale_questions', ['option_two'], unique=False)
    op.create_index(op.f('ix_scale_questions_option_two_scale'), 'scale_questions', ['option_two_scale'], unique=False)
    op.drop_index('ix_scale_questions_answer_options', table_name='scale_questions')
    op.drop_column('scale_questions', 'answer_options')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scale_questions', sa.Column('answer_options', sa.VARCHAR(length=64), nullable=True))
    op.create_index('ix_scale_questions_answer_options', 'scale_questions', ['answer_options'], unique=False)
    op.drop_index(op.f('ix_scale_questions_option_two_scale'), table_name='scale_questions')
    op.drop_index(op.f('ix_scale_questions_option_two'), table_name='scale_questions')
    op.drop_index(op.f('ix_scale_questions_option_three_scale'), table_name='scale_questions')
    op.drop_index(op.f('ix_scale_questions_option_three'), table_name='scale_questions')
    op.drop_index(op.f('ix_scale_questions_option_one_scale'), table_name='scale_questions')
    op.drop_index(op.f('ix_scale_questions_option_one'), table_name='scale_questions')
    op.drop_index(op.f('ix_scale_questions_option_four_scale'), table_name='scale_questions')
    op.drop_index(op.f('ix_scale_questions_option_four'), table_name='scale_questions')
    op.drop_index(op.f('ix_scale_questions_option_five_scale'), table_name='scale_questions')
    op.drop_index(op.f('ix_scale_questions_option_five'), table_name='scale_questions')
    op.drop_column('scale_questions', 'option_two_scale')
    op.drop_column('scale_questions', 'option_two')
    op.drop_column('scale_questions', 'option_three_scale')
    op.drop_column('scale_questions', 'option_three')
    op.drop_column('scale_questions', 'option_one_scale')
    op.drop_column('scale_questions', 'option_one')
    op.drop_column('scale_questions', 'option_four_scale')
    op.drop_column('scale_questions', 'option_four')
    op.drop_column('scale_questions', 'option_five_scale')
    op.drop_column('scale_questions', 'option_five')
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.add_column('organisations', sa.Column('order_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'organisations', 'order', ['order_id'], ['id'])
    op.add_column('options', sa.Column('text', sa.VARCHAR(length=64), nullable=True))
    op.create_index('ix_options_text', 'options', ['text'], unique=False)
    op.drop_index(op.f('ix_options_option_two'), table_name='options')
    op.drop_index(op.f('ix_options_option_three'), table_name='options')
    op.drop_index(op.f('ix_options_option_one'), table_name='options')
    op.drop_index(op.f('ix_options_option_four'), table_name='options')
    op.drop_index(op.f('ix_options_option_five'), table_name='options')
    op.drop_column('options', 'option_two')
    op.drop_column('options', 'option_three')
    op.drop_column('options', 'option_one')
    op.drop_column('options', 'option_four')
    op.drop_column('options', 'option_five')
    op.drop_index(op.f('ix_multiple_choice_questions_option_two'), table_name='multiple_choice_questions')
    op.drop_index(op.f('ix_multiple_choice_questions_option_three'), table_name='multiple_choice_questions')
    op.drop_index(op.f('ix_multiple_choice_questions_option_one'), table_name='multiple_choice_questions')
    op.drop_index(op.f('ix_multiple_choice_questions_option_four'), table_name='multiple_choice_questions')
    op.drop_index(op.f('ix_multiple_choice_questions_option_five'), table_name='multiple_choice_questions')
    op.drop_column('multiple_choice_questions', 'option_two')
    op.drop_column('multiple_choice_questions', 'option_three')
    op.drop_column('multiple_choice_questions', 'option_one')
    op.drop_column('multiple_choice_questions', 'option_four')
    op.drop_column('multiple_choice_questions', 'option_five')
    # ### end Alembic commands ###
