"""empty message

Revision ID: ff951652e333
Revises: 96e35d722836
Create Date: 2021-03-15 11:12:10.266187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff951652e333'
down_revision = '96e35d722836'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('organisation_id', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('project_id', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'questions', 'organisations', ['organisation_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'questions', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'questions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_column('questions', 'user_id')
    op.drop_column('questions', 'project_id')
    op.drop_column('questions', 'organisation_id')
    # ### end Alembic commands ###
