"""empty message

Revision ID: b15f1e3aac20
Revises: cc9d38892b24
Create Date: 2021-02-01 19:20:37.911425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b15f1e3aac20'
down_revision = 'cc9d38892b24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scale_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=90), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('options', sa.String(length=64), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scale_questions_options'), 'scale_questions', ['options'], unique=False)
    op.create_index(op.f('ix_scale_questions_title'), 'scale_questions', ['title'], unique=False)
    op.create_foreign_key(None, 'answers', 'scale_questions', ['scale_questions_id'], ['id'])
    op.create_foreign_key(None, 'association', 'scale_questions', ['scale_question_id'], ['id'])
    op.create_foreign_key(None, 'line_items', 'scale_questions', ['scale_questions_id'], ['id'])
    op.create_foreign_key(None, 'scale_answers', 'scale_questions', ['scale_question_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scale_answers', type_='foreignkey')
    op.drop_constraint(None, 'line_items', type_='foreignkey')
    op.drop_constraint(None, 'association', type_='foreignkey')
    op.drop_constraint(None, 'answers', type_='foreignkey')
    op.drop_index(op.f('ix_scale_questions_title'), table_name='scale_questions')
    op.drop_index(op.f('ix_scale_questions_options'), table_name='scale_questions')
    op.drop_table('scale_questions')
    # ### end Alembic commands ###
