"""empty message

Revision ID: cc9d38892b24
Revises: ffa374086375
Create Date: 2021-01-30 15:35:48.455291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc9d38892b24'
down_revision = 'ffa374086375'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('order_quantity', sa.Integer(), nullable=True),
    sa.Column('service_type', sa.String(length=150), nullable=True),
    sa.Column('currency', sa.String(length=150), nullable=True),
    sa.Column('order_status', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_name'), 'project', ['name'], unique=False)
    op.create_index(op.f('ix_project_order_status'), 'project', ['order_status'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('question_type', sa.String(length=64), nullable=True),
    sa.Column('multiple_choice_option_one', sa.String(length=64), nullable=True),
    sa.Column('multiple_choice_option_two', sa.String(length=64), nullable=True),
    sa.Column('multiple_choice_option_three', sa.String(length=64), nullable=True),
    sa.Column('multiple_choice_option_four', sa.String(length=64), nullable=True),
    sa.Column('multiple_choice_option_five', sa.String(length=64), nullable=True),
    sa.Column('option_one', sa.String(length=64), nullable=True),
    sa.Column('option_two', sa.String(length=64), nullable=True),
    sa.Column('option_three', sa.String(length=64), nullable=True),
    sa.Column('option_four', sa.String(length=64), nullable=True),
    sa.Column('option_five', sa.String(length=64), nullable=True),
    sa.Column('option_one_scale', sa.Integer(), nullable=True),
    sa.Column('option_two_scale', sa.Integer(), nullable=True),
    sa.Column('option_three_scale', sa.Integer(), nullable=True),
    sa.Column('option_four_scale', sa.Integer(), nullable=True),
    sa.Column('option_five_scale', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_question_type'), 'questions', ['question_type'], unique=False)
    op.create_index(op.f('ix_questions_timestamp'), 'questions', ['timestamp'], unique=False)
    op.create_table('multiple_choice_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=90), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('multiple_choice_option_one', sa.String(length=64), nullable=True),
    sa.Column('multiple_choice_option_two', sa.String(length=64), nullable=True),
    sa.Column('multiple_choice_option_three', sa.String(length=64), nullable=True),
    sa.Column('multiple_choice_option_four', sa.String(length=64), nullable=True),
    sa.Column('multiple_choice_option_five', sa.String(length=64), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_multiple_choice_questions_multiple_choice_option_five'), 'multiple_choice_questions', ['multiple_choice_option_five'], unique=False)
    op.create_index(op.f('ix_multiple_choice_questions_multiple_choice_option_four'), 'multiple_choice_questions', ['multiple_choice_option_four'], unique=False)
    op.create_index(op.f('ix_multiple_choice_questions_multiple_choice_option_one'), 'multiple_choice_questions', ['multiple_choice_option_one'], unique=False)
    op.create_index(op.f('ix_multiple_choice_questions_multiple_choice_option_three'), 'multiple_choice_questions', ['multiple_choice_option_three'], unique=False)
    op.create_index(op.f('ix_multiple_choice_questions_multiple_choice_option_two'), 'multiple_choice_questions', ['multiple_choice_option_two'], unique=False)
    op.create_index(op.f('ix_multiple_choice_questions_title'), 'multiple_choice_questions', ['title'], unique=False)
    op.create_table('scale_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=90), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('option_one', sa.String(length=64), nullable=True),
    sa.Column('option_two', sa.String(length=64), nullable=True),
    sa.Column('option_three', sa.String(length=64), nullable=True),
    sa.Column('option_four', sa.String(length=64), nullable=True),
    sa.Column('option_five', sa.String(length=64), nullable=True),
    sa.Column('option_one_scale', sa.Integer(), nullable=True),
    sa.Column('option_two_scale', sa.Integer(), nullable=True),
    sa.Column('option_three_scale', sa.Integer(), nullable=True),
    sa.Column('option_four_scale', sa.Integer(), nullable=True),
    sa.Column('option_five_scale', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scale_questions_option_five'), 'scale_questions', ['option_five'], unique=False)
    op.create_index(op.f('ix_scale_questions_option_four'), 'scale_questions', ['option_four'], unique=False)
    op.create_index(op.f('ix_scale_questions_option_one'), 'scale_questions', ['option_one'], unique=False)
    op.create_index(op.f('ix_scale_questions_option_three'), 'scale_questions', ['option_three'], unique=False)
    op.create_index(op.f('ix_scale_questions_option_two'), 'scale_questions', ['option_two'], unique=False)
    op.create_index(op.f('ix_scale_questions_title'), 'scale_questions', ['title'], unique=False)
    op.create_table('screener_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=90), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('required_answer', sa.String(length=64), nullable=True),
    sa.Column('answer_option_one', sa.String(length=64), nullable=True),
    sa.Column('answer_option_two', sa.String(length=64), nullable=True),
    sa.Column('answer_option_three', sa.String(length=64), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screener_questions_answer_option_one'), 'screener_questions', ['answer_option_one'], unique=False)
    op.create_index(op.f('ix_screener_questions_answer_option_three'), 'screener_questions', ['answer_option_three'], unique=False)
    op.create_index(op.f('ix_screener_questions_answer_option_two'), 'screener_questions', ['answer_option_two'], unique=False)
    op.create_index(op.f('ix_screener_questions_question'), 'screener_questions', ['question'], unique=False)
    op.create_index(op.f('ix_screener_questions_required_answer'), 'screener_questions', ['required_answer'], unique=False)
    op.create_table('answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_city', sa.String(), nullable=True),
    sa.Column('location_state', sa.String(), nullable=True),
    sa.Column('location_ip_address', sa.String(), nullable=True),
    sa.Column('multiple_choice_answer_one', sa.String(length=64), nullable=True),
    sa.Column('multiple_choice_answer_two', sa.String(length=64), nullable=True),
    sa.Column('multiple_choice_answer_three', sa.String(length=64), nullable=True),
    sa.Column('multiple_choice_answer_four', sa.String(length=64), nullable=True),
    sa.Column('multiple_choice_answer_five', sa.String(length=64), nullable=True),
    sa.Column('option_one_answer', sa.String(length=64), nullable=True),
    sa.Column('option_two_answer', sa.String(length=64), nullable=True),
    sa.Column('option_three_answer', sa.String(length=64), nullable=True),
    sa.Column('option_four_answer', sa.String(length=64), nullable=True),
    sa.Column('option_five_answer', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('scale_questions_id', sa.Integer(), nullable=True),
    sa.Column('multiple_choice_questions_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['multiple_choice_questions_id'], ['multiple_choice_questions.id'], ),
    sa.ForeignKeyConstraint(['scale_questions_id'], ['scale_questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answers_location_city'), 'answers', ['location_city'], unique=False)
    op.create_index(op.f('ix_answers_location_ip_address'), 'answers', ['location_ip_address'], unique=False)
    op.create_index(op.f('ix_answers_location_state'), 'answers', ['location_state'], unique=False)
    op.create_index(op.f('ix_answers_multiple_choice_answer_five'), 'answers', ['multiple_choice_answer_five'], unique=False)
    op.create_index(op.f('ix_answers_multiple_choice_answer_four'), 'answers', ['multiple_choice_answer_four'], unique=False)
    op.create_index(op.f('ix_answers_multiple_choice_answer_one'), 'answers', ['multiple_choice_answer_one'], unique=False)
    op.create_index(op.f('ix_answers_multiple_choice_answer_three'), 'answers', ['multiple_choice_answer_three'], unique=False)
    op.create_index(op.f('ix_answers_multiple_choice_answer_two'), 'answers', ['multiple_choice_answer_two'], unique=False)
    op.create_index(op.f('ix_answers_option_five_answer'), 'answers', ['option_five_answer'], unique=False)
    op.create_index(op.f('ix_answers_option_four_answer'), 'answers', ['option_four_answer'], unique=False)
    op.create_index(op.f('ix_answers_option_one_answer'), 'answers', ['option_one_answer'], unique=False)
    op.create_index(op.f('ix_answers_option_three_answer'), 'answers', ['option_three_answer'], unique=False)
    op.create_index(op.f('ix_answers_option_two_answer'), 'answers', ['option_two_answer'], unique=False)
    op.create_table('line_items',
    sa.Column('line_item_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('scale_questions_id', sa.Integer(), nullable=True),
    sa.Column('screener_questions_id', sa.Integer(), nullable=True),
    sa.Column('multiple_choice_questions_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('service_type', sa.String(length=10), nullable=True),
    sa.Column('unit_amount', sa.Float(precision=12, asdecimal=2), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['multiple_choice_questions_id'], ['multiple_choice_questions.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['scale_questions_id'], ['scale_questions.id'], ),
    sa.ForeignKeyConstraint(['screener_questions_id'], ['screener_questions.id'], ),
    sa.PrimaryKeyConstraint('line_item_id')
    )
    op.create_index(op.f('ix_line_items_name'), 'line_items', ['name'], unique=False)
    op.create_table('multiple_choice_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('multiple_choice_answer_one', sa.String(length=64), nullable=True),
    sa.Column('multiple_choice_answer_two', sa.String(length=64), nullable=True),
    sa.Column('multiple_choice_answer_three', sa.String(length=64), nullable=True),
    sa.Column('multiple_choice_answer_four', sa.String(length=64), nullable=True),
    sa.Column('multiple_choice_answer_five', sa.String(length=64), nullable=True),
    sa.Column('multiple_choice_question_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['multiple_choice_question_id'], ['multiple_choice_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_multiple_choice_answers_multiple_choice_answer_five'), 'multiple_choice_answers', ['multiple_choice_answer_five'], unique=False)
    op.create_index(op.f('ix_multiple_choice_answers_multiple_choice_answer_four'), 'multiple_choice_answers', ['multiple_choice_answer_four'], unique=False)
    op.create_index(op.f('ix_multiple_choice_answers_multiple_choice_answer_one'), 'multiple_choice_answers', ['multiple_choice_answer_one'], unique=False)
    op.create_index(op.f('ix_multiple_choice_answers_multiple_choice_answer_three'), 'multiple_choice_answers', ['multiple_choice_answer_three'], unique=False)
    op.create_index(op.f('ix_multiple_choice_answers_multiple_choice_answer_two'), 'multiple_choice_answers', ['multiple_choice_answer_two'], unique=False)
    op.create_table('scale_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scale_question_id', sa.Integer(), nullable=True),
    sa.Column('option_one_answer', sa.String(length=64), nullable=True),
    sa.Column('option_two_answer', sa.String(length=64), nullable=True),
    sa.Column('option_three_answer', sa.String(length=64), nullable=True),
    sa.Column('option_four_answer', sa.String(length=64), nullable=True),
    sa.Column('option_five_answer', sa.String(length=64), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['scale_question_id'], ['scale_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scale_answers_option_five_answer'), 'scale_answers', ['option_five_answer'], unique=False)
    op.create_index(op.f('ix_scale_answers_option_four_answer'), 'scale_answers', ['option_four_answer'], unique=False)
    op.create_index(op.f('ix_scale_answers_option_one_answer'), 'scale_answers', ['option_one_answer'], unique=False)
    op.create_index(op.f('ix_scale_answers_option_three_answer'), 'scale_answers', ['option_three_answer'], unique=False)
    op.create_index(op.f('ix_scale_answers_option_two_answer'), 'scale_answers', ['option_two_answer'], unique=False)
    op.create_table('screener_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer_option_one', sa.String(length=64), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('screener_questions_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['screener_questions_id'], ['screener_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screener_answers_answer_option_one'), 'screener_answers', ['answer_option_one'], unique=False)
    op.create_table('association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('line_items_id', sa.Integer(), nullable=True),
    sa.Column('screener_question_id', sa.Integer(), nullable=True),
    sa.Column('scale_question_id', sa.Integer(), nullable=True),
    sa.Column('multiple_choice_question_id', sa.Integer(), nullable=True),
    sa.Column('screener_answer_id', sa.Integer(), nullable=True),
    sa.Column('scale_answer_id', sa.Integer(), nullable=True),
    sa.Column('multiple_choice_answer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['line_items_id'], ['line_items.line_item_id'], ),
    sa.ForeignKeyConstraint(['multiple_choice_answer_id'], ['multiple_choice_answers.id'], ),
    sa.ForeignKeyConstraint(['multiple_choice_question_id'], ['multiple_choice_questions.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['scale_answer_id'], ['scale_answers.id'], ),
    sa.ForeignKeyConstraint(['scale_question_id'], ['scale_questions.id'], ),
    sa.ForeignKeyConstraint(['screener_answer_id'], ['screener_answers.id'], ),
    sa.ForeignKeyConstraint(['screener_question_id'], ['screener_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'order', 'project', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_table('association')
    op.drop_index(op.f('ix_screener_answers_answer_option_one'), table_name='screener_answers')
    op.drop_table('screener_answers')
    op.drop_index(op.f('ix_scale_answers_option_two_answer'), table_name='scale_answers')
    op.drop_index(op.f('ix_scale_answers_option_three_answer'), table_name='scale_answers')
    op.drop_index(op.f('ix_scale_answers_option_one_answer'), table_name='scale_answers')
    op.drop_index(op.f('ix_scale_answers_option_four_answer'), table_name='scale_answers')
    op.drop_index(op.f('ix_scale_answers_option_five_answer'), table_name='scale_answers')
    op.drop_table('scale_answers')
    op.drop_index(op.f('ix_multiple_choice_answers_multiple_choice_answer_two'), table_name='multiple_choice_answers')
    op.drop_index(op.f('ix_multiple_choice_answers_multiple_choice_answer_three'), table_name='multiple_choice_answers')
    op.drop_index(op.f('ix_multiple_choice_answers_multiple_choice_answer_one'), table_name='multiple_choice_answers')
    op.drop_index(op.f('ix_multiple_choice_answers_multiple_choice_answer_four'), table_name='multiple_choice_answers')
    op.drop_index(op.f('ix_multiple_choice_answers_multiple_choice_answer_five'), table_name='multiple_choice_answers')
    op.drop_table('multiple_choice_answers')
    op.drop_index(op.f('ix_line_items_name'), table_name='line_items')
    op.drop_table('line_items')
    op.drop_index(op.f('ix_answers_option_two_answer'), table_name='answers')
    op.drop_index(op.f('ix_answers_option_three_answer'), table_name='answers')
    op.drop_index(op.f('ix_answers_option_one_answer'), table_name='answers')
    op.drop_index(op.f('ix_answers_option_four_answer'), table_name='answers')
    op.drop_index(op.f('ix_answers_option_five_answer'), table_name='answers')
    op.drop_index(op.f('ix_answers_multiple_choice_answer_two'), table_name='answers')
    op.drop_index(op.f('ix_answers_multiple_choice_answer_three'), table_name='answers')
    op.drop_index(op.f('ix_answers_multiple_choice_answer_one'), table_name='answers')
    op.drop_index(op.f('ix_answers_multiple_choice_answer_four'), table_name='answers')
    op.drop_index(op.f('ix_answers_multiple_choice_answer_five'), table_name='answers')
    op.drop_index(op.f('ix_answers_location_state'), table_name='answers')
    op.drop_index(op.f('ix_answers_location_ip_address'), table_name='answers')
    op.drop_index(op.f('ix_answers_location_city'), table_name='answers')
    op.drop_table('answers')
    op.drop_index(op.f('ix_screener_questions_required_answer'), table_name='screener_questions')
    op.drop_index(op.f('ix_screener_questions_question'), table_name='screener_questions')
    op.drop_index(op.f('ix_screener_questions_answer_option_two'), table_name='screener_questions')
    op.drop_index(op.f('ix_screener_questions_answer_option_three'), table_name='screener_questions')
    op.drop_index(op.f('ix_screener_questions_answer_option_one'), table_name='screener_questions')
    op.drop_table('screener_questions')
    op.drop_index(op.f('ix_scale_questions_title'), table_name='scale_questions')
    op.drop_index(op.f('ix_scale_questions_option_two'), table_name='scale_questions')
    op.drop_index(op.f('ix_scale_questions_option_three'), table_name='scale_questions')
    op.drop_index(op.f('ix_scale_questions_option_one'), table_name='scale_questions')
    op.drop_index(op.f('ix_scale_questions_option_four'), table_name='scale_questions')
    op.drop_index(op.f('ix_scale_questions_option_five'), table_name='scale_questions')
    op.drop_table('scale_questions')
    op.drop_index(op.f('ix_multiple_choice_questions_title'), table_name='multiple_choice_questions')
    op.drop_index(op.f('ix_multiple_choice_questions_multiple_choice_option_two'), table_name='multiple_choice_questions')
    op.drop_index(op.f('ix_multiple_choice_questions_multiple_choice_option_three'), table_name='multiple_choice_questions')
    op.drop_index(op.f('ix_multiple_choice_questions_multiple_choice_option_one'), table_name='multiple_choice_questions')
    op.drop_index(op.f('ix_multiple_choice_questions_multiple_choice_option_four'), table_name='multiple_choice_questions')
    op.drop_index(op.f('ix_multiple_choice_questions_multiple_choice_option_five'), table_name='multiple_choice_questions')
    op.drop_table('multiple_choice_questions')
    op.drop_index(op.f('ix_questions_timestamp'), table_name='questions')
    op.drop_index(op.f('ix_questions_question_type'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_project_order_status'), table_name='project')
    op.drop_index(op.f('ix_project_name'), table_name='project')
    op.drop_table('project')
    # ### end Alembic commands ###
